apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: webapp-nmspc
  labels:
    app: employees
spec:
  imagePullSecrets:
    - name: ecr-registry-key
  containers:
    - name: webapp
      image: 844188451376.dkr.ecr.us-east-1.amazonaws.com/webapp_repo:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: "mysql-service.mysql-nmspc.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "lime"
