apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: flask
          image: 844188451376.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest
          ports:
            - containerPort: 81
          env:
            - name: MYSQL_HOST
              value: "mysql-service.final.svc.cluster.local"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "mydb"
            - name: BACKGROUND_IMAGE_KEY
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKGROUND_IMAGE_KEY
            - name: GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GROUP_NAME
            - name: GROUP_SLOGAN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GROUP_SLOGAN
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: AWS_SESSION_TOKEN
